// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BuildingPieceVariantHandle : RemoteTableHandle<EventContext, DbBuildingPieceVariant>
        {
            protected override string RemoteTableName => "building_piece_variant";

            public sealed class VariantIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(DbBuildingPieceVariant row) => row.VariantId;

                public VariantIdUniqueIndex(BuildingPieceVariantHandle table) : base(table) { }
            }

            public readonly VariantIdUniqueIndex VariantId;

            internal BuildingPieceVariantHandle(DbConnection conn) : base(conn)
            {
                VariantId = new(this);
            }

            protected override object GetPrimaryKey(DbBuildingPieceVariant row) => row.VariantId;
        }

        public readonly BuildingPieceVariantHandle BuildingPieceVariant;
    }
}
