// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BuildingPieceHandle : RemoteTableHandle<EventContext, DbBuildingPiece>
        {
            protected override string RemoteTableName => "building_piece";

            public sealed class PieceIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(DbBuildingPiece row) => row.PieceId;

                public PieceIdUniqueIndex(BuildingPieceHandle table) : base(table) { }
            }

            public readonly PieceIdUniqueIndex PieceId;

            internal BuildingPieceHandle(DbConnection conn) : base(conn)
            {
                PieceId = new(this);
            }

            protected override object GetPrimaryKey(DbBuildingPiece row) => row.PieceId;
        }

        public readonly BuildingPieceHandle BuildingPiece;
    }
}
