// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BuildingPiecePlacedHandle : RemoteTableHandle<EventContext, DbBuildingPiecePlaced>
        {
            protected override string RemoteTableName => "building_piece_placed";

            public sealed class PieceIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(DbBuildingPiecePlaced row) => row.PieceId;

                public PieceIdUniqueIndex(BuildingPiecePlacedHandle table) : base(table) { }
            }

            public readonly PieceIdUniqueIndex PieceId;

            internal BuildingPiecePlacedHandle(DbConnection conn) : base(conn)
            {
                PieceId = new(this);
            }

            protected override object GetPrimaryKey(DbBuildingPiecePlaced row) => row.PieceId;
        }

        public readonly BuildingPiecePlacedHandle BuildingPiecePlaced;
    }
}
