// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CreativeCameraHandle : RemoteTableHandle<EventContext, CreativeCamera>
        {
            protected override string RemoteTableName => "creative_camera";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(CreativeCamera row) => row.Identity;

                public IdentityUniqueIndex(CreativeCameraHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            internal CreativeCameraHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
            }

            protected override object GetPrimaryKey(CreativeCamera row) => row.Identity;
        }

        public readonly CreativeCameraHandle CreativeCamera;
    }
}
