// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class InventoryHandle : RemoteTableHandle<EventContext, Inventory>
        {
            protected override string RemoteTableName => "inventory";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(Inventory row) => row.Identity;

                public IdentityUniqueIndex(InventoryHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            internal InventoryHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
            }

            protected override object GetPrimaryKey(Inventory row) => row.Identity;
        }

        public readonly InventoryHandle Inventory;
    }
}
