// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ItemHandle : RemoteTableHandle<EventContext, Item>
        {
            protected override string RemoteTableName => "item";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Item row) => row.Id;

                public IdUniqueIndex(ItemHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ItemHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(Item row) => row.Id;
        }

        public readonly ItemHandle Item;
    }
}
