// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class WorldSpawnHandle : RemoteTableHandle<EventContext, WorldSpawn>
        {
            protected override string RemoteTableName => "world_spawn";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(WorldSpawn row) => row.Id;

                public IdUniqueIndex(WorldSpawnHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal WorldSpawnHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(WorldSpawn row) => row.Id;
        }

        public readonly WorldSpawnHandle WorldSpawn;
    }
}
