// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ApplyDamageHandler(ReducerEventContext ctx, SpacetimeDB.Identity targetIdentity, float damage);
        public event ApplyDamageHandler? OnApplyDamage;

        public void ApplyDamage(SpacetimeDB.Identity targetIdentity, float damage)
        {
            conn.InternalCallReducer(new Reducer.ApplyDamage(targetIdentity, damage), this.SetCallReducerFlags.ApplyDamageFlags);
        }

        public bool InvokeApplyDamage(ReducerEventContext ctx, Reducer.ApplyDamage args)
        {
            if (OnApplyDamage == null) return false;
            OnApplyDamage(
                ctx,
                args.TargetIdentity,
                args.Damage
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ApplyDamage : Reducer, IReducerArgs
        {
            [DataMember(Name = "target_identity")]
            public SpacetimeDB.Identity TargetIdentity;
            [DataMember(Name = "damage")]
            public float Damage;

            public ApplyDamage(
                SpacetimeDB.Identity TargetIdentity,
                float Damage
            )
            {
                this.TargetIdentity = TargetIdentity;
                this.Damage = Damage;
            }

            public ApplyDamage()
            {
            }

            string IReducerArgs.ReducerName => "apply_damage";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ApplyDamageFlags;
        public void ApplyDamage(CallReducerFlags flags) => ApplyDamageFlags = flags;
    }
}
