// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void InventoryRemoveItemHandler(ReducerEventContext ctx, uint itemId, uint quantity);
        public event InventoryRemoveItemHandler? OnInventoryRemoveItem;

        public void InventoryRemoveItem(uint itemId, uint quantity)
        {
            conn.InternalCallReducer(new Reducer.InventoryRemoveItem(itemId, quantity), this.SetCallReducerFlags.InventoryRemoveItemFlags);
        }

        public bool InvokeInventoryRemoveItem(ReducerEventContext ctx, Reducer.InventoryRemoveItem args)
        {
            if (OnInventoryRemoveItem == null) return false;
            OnInventoryRemoveItem(
                ctx,
                args.ItemId,
                args.Quantity
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class InventoryRemoveItem : Reducer, IReducerArgs
        {
            [DataMember(Name = "item_id")]
            public uint ItemId;
            [DataMember(Name = "quantity")]
            public uint Quantity;

            public InventoryRemoveItem(
                uint ItemId,
                uint Quantity
            )
            {
                this.ItemId = ItemId;
                this.Quantity = Quantity;
            }

            public InventoryRemoveItem()
            {
            }

            string IReducerArgs.ReducerName => "inventory_remove_item";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags InventoryRemoveItemFlags;
        public void InventoryRemoveItem(CallReducerFlags flags) => InventoryRemoveItemFlags = flags;
    }
}
