// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void MoveCreativeCameraHandler(ReducerEventContext ctx, DbVector3 position, DbVector3 rotation);
        public event MoveCreativeCameraHandler? OnMoveCreativeCamera;

        public void MoveCreativeCamera(DbVector3 position, DbVector3 rotation)
        {
            conn.InternalCallReducer(new Reducer.MoveCreativeCamera(position, rotation), this.SetCallReducerFlags.MoveCreativeCameraFlags);
        }

        public bool InvokeMoveCreativeCamera(ReducerEventContext ctx, Reducer.MoveCreativeCamera args)
        {
            if (OnMoveCreativeCamera == null) return false;
            OnMoveCreativeCamera(
                ctx,
                args.Position,
                args.Rotation
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class MoveCreativeCamera : Reducer, IReducerArgs
        {
            [DataMember(Name = "position")]
            public DbVector3 Position;
            [DataMember(Name = "rotation")]
            public DbVector3 Rotation;

            public MoveCreativeCamera(
                DbVector3 Position,
                DbVector3 Rotation
            )
            {
                this.Position = Position;
                this.Rotation = Rotation;
            }

            public MoveCreativeCamera()
            {
                this.Position = new();
                this.Rotation = new();
            }

            string IReducerArgs.ReducerName => "move_creative_camera";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags MoveCreativeCameraFlags;
        public void MoveCreativeCamera(CallReducerFlags flags) => MoveCreativeCameraFlags = flags;
    }
}
