// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PlaceBuildingPieceHandler(ReducerEventContext ctx, DbBuildingPieceType pieceType, DbVector3 position, DbVector3 rotation);
        public event PlaceBuildingPieceHandler? OnPlaceBuildingPiece;

        public void PlaceBuildingPiece(DbBuildingPieceType pieceType, DbVector3 position, DbVector3 rotation)
        {
            conn.InternalCallReducer(new Reducer.PlaceBuildingPiece(pieceType, position, rotation), this.SetCallReducerFlags.PlaceBuildingPieceFlags);
        }

        public bool InvokePlaceBuildingPiece(ReducerEventContext ctx, Reducer.PlaceBuildingPiece args)
        {
            if (OnPlaceBuildingPiece == null) return false;
            OnPlaceBuildingPiece(
                ctx,
                args.PieceType,
                args.Position,
                args.Rotation
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PlaceBuildingPiece : Reducer, IReducerArgs
        {
            [DataMember(Name = "piece_type")]
            public DbBuildingPieceType PieceType;
            [DataMember(Name = "position")]
            public DbVector3 Position;
            [DataMember(Name = "rotation")]
            public DbVector3 Rotation;

            public PlaceBuildingPiece(
                DbBuildingPieceType PieceType,
                DbVector3 Position,
                DbVector3 Rotation
            )
            {
                this.PieceType = PieceType;
                this.Position = Position;
                this.Rotation = Rotation;
            }

            public PlaceBuildingPiece()
            {
                this.Position = new();
                this.Rotation = new();
            }

            string IReducerArgs.ReducerName => "place_building_piece";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags PlaceBuildingPieceFlags;
        public void PlaceBuildingPiece(CallReducerFlags flags) => PlaceBuildingPieceFlags = flags;
    }
}
