// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PlayerSetLookDirectionHandler(ReducerEventContext ctx, DbVector2 lookDirection);
        public event PlayerSetLookDirectionHandler? OnPlayerSetLookDirection;

        public void PlayerSetLookDirection(DbVector2 lookDirection)
        {
            conn.InternalCallReducer(new Reducer.PlayerSetLookDirection(lookDirection), this.SetCallReducerFlags.PlayerSetLookDirectionFlags);
        }

        public bool InvokePlayerSetLookDirection(ReducerEventContext ctx, Reducer.PlayerSetLookDirection args)
        {
            if (OnPlayerSetLookDirection == null) return false;
            OnPlayerSetLookDirection(
                ctx,
                args.LookDirection
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PlayerSetLookDirection : Reducer, IReducerArgs
        {
            [DataMember(Name = "look_direction")]
            public DbVector2 LookDirection;

            public PlayerSetLookDirection(DbVector2 LookDirection)
            {
                this.LookDirection = LookDirection;
            }

            public PlayerSetLookDirection()
            {
                this.LookDirection = new();
            }

            string IReducerArgs.ReducerName => "player_set_look_direction";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags PlayerSetLookDirectionFlags;
        public void PlayerSetLookDirection(CallReducerFlags flags) => PlayerSetLookDirectionFlags = flags;
    }
}
