// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PlayerResetHealthHandler(ReducerEventContext ctx, SpacetimeDB.Identity targetIdentity);
        public event PlayerResetHealthHandler? OnPlayerResetHealth;

        public void PlayerResetHealth(SpacetimeDB.Identity targetIdentity)
        {
            conn.InternalCallReducer(new Reducer.PlayerResetHealth(targetIdentity), this.SetCallReducerFlags.PlayerResetHealthFlags);
        }

        public bool InvokePlayerResetHealth(ReducerEventContext ctx, Reducer.PlayerResetHealth args)
        {
            if (OnPlayerResetHealth == null) return false;
            OnPlayerResetHealth(
                ctx,
                args.TargetIdentity
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PlayerResetHealth : Reducer, IReducerArgs
        {
            [DataMember(Name = "target_identity")]
            public SpacetimeDB.Identity TargetIdentity;

            public PlayerResetHealth(SpacetimeDB.Identity TargetIdentity)
            {
                this.TargetIdentity = TargetIdentity;
            }

            public PlayerResetHealth()
            {
            }

            string IReducerArgs.ReducerName => "player_reset_health";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags PlayerResetHealthFlags;
        public void PlayerResetHealth(CallReducerFlags flags) => PlayerResetHealthFlags = flags;
    }
}
