// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PlayerApplyDamageHandler(ReducerEventContext ctx, SpacetimeDB.Identity targetIdentity, float damage);
        public event PlayerApplyDamageHandler? OnPlayerApplyDamage;

        public void PlayerApplyDamage(SpacetimeDB.Identity targetIdentity, float damage)
        {
            conn.InternalCallReducer(new Reducer.PlayerApplyDamage(targetIdentity, damage), this.SetCallReducerFlags.PlayerApplyDamageFlags);
        }

        public bool InvokePlayerApplyDamage(ReducerEventContext ctx, Reducer.PlayerApplyDamage args)
        {
            if (OnPlayerApplyDamage == null) return false;
            OnPlayerApplyDamage(
                ctx,
                args.TargetIdentity,
                args.Damage
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PlayerApplyDamage : Reducer, IReducerArgs
        {
            [DataMember(Name = "target_identity")]
            public SpacetimeDB.Identity TargetIdentity;
            [DataMember(Name = "damage")]
            public float Damage;

            public PlayerApplyDamage(
                SpacetimeDB.Identity TargetIdentity,
                float Damage
            )
            {
                this.TargetIdentity = TargetIdentity;
                this.Damage = Damage;
            }

            public PlayerApplyDamage()
            {
            }

            string IReducerArgs.ReducerName => "player_apply_damage";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags PlayerApplyDamageFlags;
        public void PlayerApplyDamage(CallReducerFlags flags) => PlayerApplyDamageFlags = flags;
    }
}
