// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RemoveBuildingPieceHandler(ReducerEventContext ctx, uint pieceId);
        public event RemoveBuildingPieceHandler? OnRemoveBuildingPiece;

        public void RemoveBuildingPiece(uint pieceId)
        {
            conn.InternalCallReducer(new Reducer.RemoveBuildingPiece(pieceId), this.SetCallReducerFlags.RemoveBuildingPieceFlags);
        }

        public bool InvokeRemoveBuildingPiece(ReducerEventContext ctx, Reducer.RemoveBuildingPiece args)
        {
            if (OnRemoveBuildingPiece == null) return false;
            OnRemoveBuildingPiece(
                ctx,
                args.PieceId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RemoveBuildingPiece : Reducer, IReducerArgs
        {
            [DataMember(Name = "piece_id")]
            public uint PieceId;

            public RemoveBuildingPiece(uint PieceId)
            {
                this.PieceId = PieceId;
            }

            public RemoveBuildingPiece()
            {
            }

            string IReducerArgs.ReducerName => "remove_building_piece";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags RemoveBuildingPieceFlags;
        public void RemoveBuildingPiece(CallReducerFlags flags) => RemoveBuildingPieceFlags = flags;
    }
}
