// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ResetPlayerHealthHandler(ReducerEventContext ctx, SpacetimeDB.Identity targetIdentity);
        public event ResetPlayerHealthHandler? OnResetPlayerHealth;

        public void ResetPlayerHealth(SpacetimeDB.Identity targetIdentity)
        {
            conn.InternalCallReducer(new Reducer.ResetPlayerHealth(targetIdentity), this.SetCallReducerFlags.ResetPlayerHealthFlags);
        }

        public bool InvokeResetPlayerHealth(ReducerEventContext ctx, Reducer.ResetPlayerHealth args)
        {
            if (OnResetPlayerHealth == null) return false;
            OnResetPlayerHealth(
                ctx,
                args.TargetIdentity
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ResetPlayerHealth : Reducer, IReducerArgs
        {
            [DataMember(Name = "target_identity")]
            public SpacetimeDB.Identity TargetIdentity;

            public ResetPlayerHealth(SpacetimeDB.Identity TargetIdentity)
            {
                this.TargetIdentity = TargetIdentity;
            }

            public ResetPlayerHealth()
            {
            }

            string IReducerArgs.ReducerName => "reset_player_health";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ResetPlayerHealthFlags;
        public void ResetPlayerHealth(CallReducerFlags flags) => ResetPlayerHealthFlags = flags;
    }
}
