// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetCreativeCameraEnabledHandler(ReducerEventContext ctx, bool enabled);
        public event SetCreativeCameraEnabledHandler? OnSetCreativeCameraEnabled;

        public void SetCreativeCameraEnabled(bool enabled)
        {
            conn.InternalCallReducer(new Reducer.SetCreativeCameraEnabled(enabled), this.SetCallReducerFlags.SetCreativeCameraEnabledFlags);
        }

        public bool InvokeSetCreativeCameraEnabled(ReducerEventContext ctx, Reducer.SetCreativeCameraEnabled args)
        {
            if (OnSetCreativeCameraEnabled == null) return false;
            OnSetCreativeCameraEnabled(
                ctx,
                args.Enabled
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetCreativeCameraEnabled : Reducer, IReducerArgs
        {
            [DataMember(Name = "enabled")]
            public bool Enabled;

            public SetCreativeCameraEnabled(bool Enabled)
            {
                this.Enabled = Enabled;
            }

            public SetCreativeCameraEnabled()
            {
            }

            string IReducerArgs.ReducerName => "set_creative_camera_enabled";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SetCreativeCameraEnabledFlags;
        public void SetCreativeCameraEnabled(CallReducerFlags flags) => SetCreativeCameraEnabledFlags = flags;
    }
}
