// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetWorldSpawnHandler(ReducerEventContext ctx, uint id, float x, float y, float z, float rx, float ry, float rz);
        public event SetWorldSpawnHandler? OnSetWorldSpawn;

        public void SetWorldSpawn(uint id, float x, float y, float z, float rx, float ry, float rz)
        {
            conn.InternalCallReducer(new Reducer.SetWorldSpawn(id, x, y, z, rx, ry, rz), this.SetCallReducerFlags.SetWorldSpawnFlags);
        }

        public bool InvokeSetWorldSpawn(ReducerEventContext ctx, Reducer.SetWorldSpawn args)
        {
            if (OnSetWorldSpawn == null) return false;
            OnSetWorldSpawn(
                ctx,
                args.Id,
                args.X,
                args.Y,
                args.Z,
                args.Rx,
                args.Ry,
                args.Rz
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetWorldSpawn : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public uint Id;
            [DataMember(Name = "x")]
            public float X;
            [DataMember(Name = "y")]
            public float Y;
            [DataMember(Name = "z")]
            public float Z;
            [DataMember(Name = "rx")]
            public float Rx;
            [DataMember(Name = "ry")]
            public float Ry;
            [DataMember(Name = "rz")]
            public float Rz;

            public SetWorldSpawn(
                uint Id,
                float X,
                float Y,
                float Z,
                float Rx,
                float Ry,
                float Rz
            )
            {
                this.Id = Id;
                this.X = X;
                this.Y = Y;
                this.Z = Z;
                this.Rx = Rx;
                this.Ry = Ry;
                this.Rz = Rz;
            }

            public SetWorldSpawn()
            {
            }

            string IReducerArgs.ReducerName => "set_world_spawn";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SetWorldSpawnFlags;
        public void SetWorldSpawn(CallReducerFlags flags) => SetWorldSpawnFlags = flags;
    }
}
