// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetWorldSpawnHandler(ReducerEventContext ctx, uint id, DbVector3 position, DbVector3 rotation);
        public event SetWorldSpawnHandler? OnSetWorldSpawn;

        public void SetWorldSpawn(uint id, DbVector3 position, DbVector3 rotation)
        {
            conn.InternalCallReducer(new Reducer.SetWorldSpawn(id, position, rotation), this.SetCallReducerFlags.SetWorldSpawnFlags);
        }

        public bool InvokeSetWorldSpawn(ReducerEventContext ctx, Reducer.SetWorldSpawn args)
        {
            if (OnSetWorldSpawn == null) return false;
            OnSetWorldSpawn(
                ctx,
                args.Id,
                args.Position,
                args.Rotation
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetWorldSpawn : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public uint Id;
            [DataMember(Name = "position")]
            public DbVector3 Position;
            [DataMember(Name = "rotation")]
            public DbVector3 Rotation;

            public SetWorldSpawn(
                uint Id,
                DbVector3 Position,
                DbVector3 Rotation
            )
            {
                this.Id = Id;
                this.Position = Position;
                this.Rotation = Rotation;
            }

            public SetWorldSpawn()
            {
                this.Position = new();
                this.Rotation = new();
            }

            string IReducerArgs.ReducerName => "set_world_spawn";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SetWorldSpawnFlags;
        public void SetWorldSpawn(CallReducerFlags flags) => SetWorldSpawnFlags = flags;
    }
}
