// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ToggleCreativeCameraHandler(ReducerEventContext ctx, bool enabled);
        public event ToggleCreativeCameraHandler? OnToggleCreativeCamera;

        public void ToggleCreativeCamera(bool enabled)
        {
            conn.InternalCallReducer(new Reducer.ToggleCreativeCamera(enabled), this.SetCallReducerFlags.ToggleCreativeCameraFlags);
        }

        public bool InvokeToggleCreativeCamera(ReducerEventContext ctx, Reducer.ToggleCreativeCamera args)
        {
            if (OnToggleCreativeCamera == null) return false;
            OnToggleCreativeCamera(
                ctx,
                args.Enabled
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ToggleCreativeCamera : Reducer, IReducerArgs
        {
            [DataMember(Name = "enabled")]
            public bool Enabled;

            public ToggleCreativeCamera(bool Enabled)
            {
                this.Enabled = Enabled;
            }

            public ToggleCreativeCamera()
            {
            }

            string IReducerArgs.ReducerName => "toggle_creative_camera";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ToggleCreativeCameraFlags;
        public void ToggleCreativeCamera(CallReducerFlags flags) => ToggleCreativeCameraFlags = flags;
    }
}
