// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void WorldSpawnSetHandler(ReducerEventContext ctx, uint id, DbVector3 position, DbVector3 rotation);
        public event WorldSpawnSetHandler? OnWorldSpawnSet;

        public void WorldSpawnSet(uint id, DbVector3 position, DbVector3 rotation)
        {
            conn.InternalCallReducer(new Reducer.WorldSpawnSet(id, position, rotation), this.SetCallReducerFlags.WorldSpawnSetFlags);
        }

        public bool InvokeWorldSpawnSet(ReducerEventContext ctx, Reducer.WorldSpawnSet args)
        {
            if (OnWorldSpawnSet == null) return false;
            OnWorldSpawnSet(
                ctx,
                args.Id,
                args.Position,
                args.Rotation
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class WorldSpawnSet : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public uint Id;
            [DataMember(Name = "position")]
            public DbVector3 Position;
            [DataMember(Name = "rotation")]
            public DbVector3 Rotation;

            public WorldSpawnSet(
                uint Id,
                DbVector3 Position,
                DbVector3 Rotation
            )
            {
                this.Id = Id;
                this.Position = Position;
                this.Rotation = Rotation;
            }

            public WorldSpawnSet()
            {
                this.Position = new();
                this.Rotation = new();
            }

            string IReducerArgs.ReducerName => "world_spawn_set";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags WorldSpawnSetFlags;
        public void WorldSpawnSet(CallReducerFlags flags) => WorldSpawnSetFlags = flags;
    }
}
