// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class DbAnimationState
    {
        [DataMember(Name = "horizontal_movement")]
        public float HorizontalMovement;
        [DataMember(Name = "vertical_movement")]
        public float VerticalMovement;
        [DataMember(Name = "combo_count")]
        public uint ComboCount;
        [DataMember(Name = "is_moving")]
        public bool IsMoving;
        [DataMember(Name = "is_grounded")]
        public bool IsGrounded;
        [DataMember(Name = "is_jumping")]
        public bool IsJumping;
        [DataMember(Name = "is_attacking")]
        public bool IsAttacking;

        public DbAnimationState(
            float HorizontalMovement,
            float VerticalMovement,
            uint ComboCount,
            bool IsMoving,
            bool IsGrounded,
            bool IsJumping,
            bool IsAttacking
        )
        {
            this.HorizontalMovement = HorizontalMovement;
            this.VerticalMovement = VerticalMovement;
            this.ComboCount = ComboCount;
            this.IsMoving = IsMoving;
            this.IsGrounded = IsGrounded;
            this.IsJumping = IsJumping;
            this.IsAttacking = IsAttacking;
        }

        public DbAnimationState()
        {
        }
    }
}
