// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class DbBuildingCost
    {
        [DataMember(Name = "item_id")]
        public uint ItemId;
        [DataMember(Name = "quantity")]
        public uint Quantity;

        public DbBuildingCost(
            uint ItemId,
            uint Quantity
        )
        {
            this.ItemId = ItemId;
            this.Quantity = Quantity;
        }

        public DbBuildingCost()
        {
        }
    }
}
