// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class DbBuildingPiecePlaced
    {
        [DataMember(Name = "piece_id")]
        public uint PieceId;
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;
        [DataMember(Name = "variant_id")]
        public uint VariantId;
        [DataMember(Name = "position")]
        public DbVector3 Position;
        [DataMember(Name = "rotation")]
        public DbVector3 Rotation;

        public DbBuildingPiecePlaced(
            uint PieceId,
            SpacetimeDB.Identity Owner,
            uint VariantId,
            DbVector3 Position,
            DbVector3 Rotation
        )
        {
            this.PieceId = PieceId;
            this.Owner = Owner;
            this.VariantId = VariantId;
            this.Position = Position;
            this.Rotation = Rotation;
        }

        public DbBuildingPiecePlaced()
        {
            this.Position = new();
            this.Rotation = new();
        }
    }
}
