// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class DbBuildingPieceVariant
    {
        [DataMember(Name = "variant_id")]
        public uint VariantId;
        [DataMember(Name = "piece_type")]
        public DbBuildingPieceType PieceType;
        [DataMember(Name = "variant_name")]
        public string VariantName;
        [DataMember(Name = "build_cost")]
        public uint BuildCost;
        [DataMember(Name = "max_health")]
        public float MaxHealth;

        public DbBuildingPieceVariant(
            uint VariantId,
            DbBuildingPieceType PieceType,
            string VariantName,
            uint BuildCost,
            float MaxHealth
        )
        {
            this.VariantId = VariantId;
            this.PieceType = PieceType;
            this.VariantName = VariantName;
            this.BuildCost = BuildCost;
            this.MaxHealth = MaxHealth;
        }

        public DbBuildingPieceVariant()
        {
            this.VariantName = "";
        }
    }
}
