// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Inventory
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "size")]
        public uint Size;
        [DataMember(Name = "items")]
        public System.Collections.Generic.List<ItemRef> Items;

        public Inventory(
            SpacetimeDB.Identity Identity,
            uint Size,
            System.Collections.Generic.List<ItemRef> Items
        )
        {
            this.Identity = Identity;
            this.Size = Size;
            this.Items = Items;
        }

        public Inventory()
        {
            this.Items = new();
        }
    }
}
