// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Item
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "description")]
        public string Description;
        [DataMember(Name = "weight")]
        public float Weight;

        public Item(
            uint Id,
            string Name,
            string Description,
            float Weight
        )
        {
            this.Id = Id;
            this.Name = Name;
            this.Description = Description;
            this.Weight = Weight;
        }

        public Item()
        {
            this.Name = "";
            this.Description = "";
        }
    }
}
