// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Player
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "player_id")]
        public uint PlayerId;
        [DataMember(Name = "position")]
        public DbVector3 Position;
        [DataMember(Name = "rotation")]
        public DbVector3 Rotation;

        public Player(
            SpacetimeDB.Identity Identity,
            uint PlayerId,
            DbVector3 Position,
            DbVector3 Rotation
        )
        {
            this.Identity = Identity;
            this.PlayerId = PlayerId;
            this.Position = Position;
            this.Rotation = Rotation;
        }

        public Player()
        {
            this.Position = new();
            this.Rotation = new();
        }
    }
}
