// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Player
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "player_id")]
        public uint PlayerId;
        [DataMember(Name = "online")]
        public bool Online;
        [DataMember(Name = "position")]
        public DbVector3 Position;
        [DataMember(Name = "rotation")]
        public DbVector3 Rotation;
        [DataMember(Name = "look_direction")]
        public DbVector2 LookDirection;
        [DataMember(Name = "animation_state")]
        public DbAnimationState AnimationState;
        [DataMember(Name = "health")]
        public float Health;
        [DataMember(Name = "max_health")]
        public float MaxHealth;

        public Player(
            SpacetimeDB.Identity Identity,
            uint PlayerId,
            bool Online,
            DbVector3 Position,
            DbVector3 Rotation,
            DbVector2 LookDirection,
            DbAnimationState AnimationState,
            float Health,
            float MaxHealth
        )
        {
            this.Identity = Identity;
            this.PlayerId = PlayerId;
            this.Online = Online;
            this.Position = Position;
            this.Rotation = Rotation;
            this.LookDirection = LookDirection;
            this.AnimationState = AnimationState;
            this.Health = Health;
            this.MaxHealth = MaxHealth;
        }

        public Player()
        {
            this.Position = new();
            this.Rotation = new();
            this.LookDirection = new();
            this.AnimationState = new();
        }
    }
}
