// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WorldSpawn
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "position")]
        public DbVector3 Position;
        [DataMember(Name = "rotation")]
        public DbVector3 Rotation;

        public WorldSpawn(
            uint Id,
            DbVector3 Position,
            DbVector3 Rotation
        )
        {
            this.Id = Id;
            this.Position = Position;
            this.Rotation = Rotation;
        }

        public WorldSpawn()
        {
            this.Position = new();
            this.Rotation = new();
        }
    }
}
